# Generated by Django 3.2.8 on 2021-10-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoritem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='vendoritem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orderitem'),
        ),
    ]
