# Generated by Django 3.2.8 on 2021-10-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211031_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
