# Generated by Django 3.2.8 on 2021-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vendor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
